project_id = "tzybedakdkjwzygbjtde"

[api]
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API
# endpoints. public and storage are always included.
schemas = ["flows", "public", "storage", "graphql_public"]

# Extra schemas to add to the search_path of every request. public is always included.
extra_search_path = ["flows", "public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 17

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
file_size_limit = "50MiB"

[auth]
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000"]
# Defaults to 3600 (1 hour), maximum 604,800 seconds (one week).
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[auth.hook.custom_access_token]
enabled = true
uri = "pg-functions://postgres/public/customer_jwt_token_hook"

[analytics]
enabled = true
port = 54327
vector_port = 54328
