name: MyEnergy Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Sqitch install
        run: docker pull sqitch/sqitch && curl -L https://git.io/JJKCn -o /usr/local/bin/sqitch && chmod +x /usr/local/bin/sqitch && sqitch --help

      - name: Start Timescale
        run: bin/ts-up

      # Looking at the logs it takes about 15 seconds so give a little buffer.
      # IF we don't do this the migrations below fail.
      - name: Wait Timescale
        run: sleep 25

      - name: Migrations
        run: cd sqitch && sqitch deploy --verbose && cd -

      # uncomment the following to be able to ssh in and investigate an issue:
      #
      # - name: Setup tmate session
      #   if: success() || failure()
      #   uses: mxschmitt/action-tmate@v3

      - name: create .pgpass for seed script
        run: mkdir -p /tmp/psql-script/ && echo "*:*:postgres:postgres:postgres" > /tmp/psql-script/.pgpass && chmod 0600 /tmp/psql-script/.pgpass

      - name: Seed
        run: bin/seed

      - name: Test
        run: bin/test

      # TODO: Was using supabase lint - replace with something else
      # - name: Lint
      #   run: bin/supa-lint
