name: MyEnergy Build and Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      timescaledb:
        image: timescale/timescaledb:latest-pg17
        env:
          POSTGRES_USER: tsdbadmin
          POSTGRES_PASSWORD: tsdbadmin
          POSTGRES_DB: tsdb
        ports:
          - 25432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Sqitch install
        run: docker pull sqitch/sqitch && curl -L https://git.io/JJKCn -o /usr/local/bin/sqitch && chmod +x /usr/local/bin/sqitch && sqitch --help

      - name: Migrations
        run: cd sqitch && sqitch deploy --target timescale-ci --verbose && cd -

      # uncomment the following to be able to ssh in and investigate an issue:
      #
      # - name: Setup tmate session
      #   if: success() || failure()
      #   uses: mxschmitt/action-tmate@v3

      - name: create .pgpass for seed script
        run: mkdir -p /tmp/psql-script/ && echo "*:*:*:tsdbadmin:tsdbadmin" > /tmp/psql-script/.pgpass && chmod 0600 /tmp/psql-script/.pgpass

      - name: Seed
        run: bin/seed

      - name: Test
        env:
          PGPASSWORD: tsdbadmin
        run: bin/test

      # TODO: Was using supabase lint - replace with something else
      # - name: Lint
      #   run: bin/supa-lint
